"""
Model adaptation tests: the existing-parameter pre-pass, the demo-mode
structural search (api=:none — no LLM call, no network access, no API key
required), retry-loop mechanics, the opt-in escalation path, and the pure
combinatorial/statistical helpers behind them.

Relies on `problem`, `base_circuit`, `r1`, `cap`, `vref`, `generate_true_data`
and the electrical-circuit constants already defined by electrical_fixture.jl,
which test_electrical.jl includes once — see the ordering note in
runtests.jl. This file must not `include` the fixture again: several of its
top-level bindings are `const`, and Julia rejects redefining a `const` to a
new object.
"""

using Test

@testset "Model Adaptation" begin

    @testset "Existing-parameter pre-pass resolves a pure parameter drift" begin
        # No structural change at all: the "true" data is generated by the
        # SAME RC topology as `base_circuit`, just with a different R1. This
        # must be resolved via the AdaptableParam re-fit, without entering the
        # structural search or making any LLM call.
        R1_TRUE = 1.6 * R1_VAL
        analytic_data(tspan, n_points) = begin
            times  = collect(range(tspan[1], tspan[2]; length = n_points))
            states = reshape(V_SRC .* (1 .- exp.(-times ./ (R1_TRUE * C_VAL))), 1, :)
            (times, states)
        end
        data_times, data_states = analytic_data(T_SPAN, 200)

        param_problem = AIRMEDProblem(;
            name              = "RC — parameter drift only",
            model             = base_circuit,
            adaptable_params  = [AdaptableParam(:r1_R, r1.R, R1_VAL)],
            data_source       = FunctionDataSource(analytic_data),
            tspan             = T_SPAN,
            u0                = [cap.v => 0.0],
            p0                = [r1.R => R1_VAL, cap.C => C_VAL, vref.k => V_SRC],
            observable_states = [cap.v],
        )

        result = propose_model_adaptation(param_problem; data_times, data_states, api = :none)

        @test result.success
        @test isempty(result.proposals)
        @test length(result.parameter_adjustments) == 1
        adj = result.parameter_adjustments[1]
        @test adj.name == :r1_R
        @test isapprox(adj.new_value, R1_TRUE; rtol = 0.1)
        @test result.raw_response == "[parameter-only pre-pass — no LLM call needed]"
    end

    @testset "Demo-mode structural search runs the retry loop without an LLM" begin
        data_times, data_states = generate_true_data(T_SPAN, 100)

        result = propose_model_adaptation(
            problem; data_times, data_states,
            api = :none, max_retries = 1, fit_iters = 100,
        )

        @test result.api == :none
        @test result.success
        @test !isempty(result.proposals)
        @test !isempty(result.conversation)
        @test length(result.conversation) <= 2   # max_retries + 1
        @test all(ex -> occursin("demo mode", lowercase(ex.raw_response)), result.conversation)
        @test !isempty(result.generated_code)

        summary = model_adaptation_summary(result)
        @test occursin("AIRMED Model Adaptation", summary)
        @test occursin("Proposals", summary)
    end

    @testset "max_retries bounds the number of attempts" begin
        data_times, data_states = generate_true_data(T_SPAN, 100)
        result = propose_model_adaptation(
            problem; data_times, data_states,
            api = :none, max_retries = 0, fit_iters = 50,
        )
        @test length(result.conversation) == 1
    end

    @testset "escalate_on_inadequate_structure rejects an attempt that could not be fitted" begin
        data_times, data_states = generate_true_data(T_SPAN, 50)
        result = propose_model_adaptation(
            problem; data_times, data_states,
            api = :none, max_retries = 0, fit_params = false,
            escalate_on_inadequate_structure = true,
        )
        @test !result.success
        @test occursin("REJECTED", result.message)
        @test !isempty(result.escalation)
        @test occursin("explanation", result.escalation)
        @test occursin("recommendation", result.escalation)
    end

    @testset "escalate_on_inadequate_structure is opt-in (default leaves the result usable)" begin
        data_times, data_states = generate_true_data(T_SPAN, 50)
        result = propose_model_adaptation(
            problem; data_times, data_states,
            api = :none, max_retries = 0, fit_params = false,
        )
        @test result.success
        @test isempty(result.escalation)
    end

    @testset "_proposals_from_guesses enumerates demo-mode combinations deterministically" begin
        p1 = AIRMED._proposals_from_guesses(problem.component_hooks, problem.component_guesses; attempt = 1)
        @test length(p1) == 1
        @test p1[1].component_type == :Resistor
        @test p1[1].port_a == problem.component_hooks[1].port_a

        # Single-hook combinations are exhausted first (2 hooks x 3 types = 6),
        # so attempt 7 is the first combination that fills BOTH hooks.
        p7 = AIRMED._proposals_from_guesses(problem.component_hooks, problem.component_guesses; attempt = 7)
        @test length(p7) == 2
        @test all(p -> p.component_type == :Resistor, p7)

        # Beyond the last combination, enumeration returns nothing usable.
        n_combos = (length(problem.component_guesses) + 1)^length(problem.component_hooks) - 1
        p_over = AIRMED._proposals_from_guesses(problem.component_hooks, problem.component_guesses;
                                                attempt = n_combos + 1)
        @test isempty(p_over)

        # Fingerprints identify a proposal set independent of insertion order.
        fp_a = AIRMED._proposal_fingerprint(p7)
        fp_b = AIRMED._proposal_fingerprint(reverse(p7))
        @test fp_a == fp_b
        @test AIRMED._proposal_fingerprint(p1) != fp_a
    end

    @testset "_hl_accept_factor" begin
        # w=1 is the retry loop's own threshold (see propose_model_adaptation);
        # ties this test to the ~1.12x figure the escalation logic is built on.
        @test isapprox(AIRMED._hl_accept_factor(200, 1), 1.117; atol = 0.01)
        @test AIRMED._hl_accept_factor(200, 1) > 1.0
        # Approaches 1 as the number of independent samples grows.
        @test AIRMED._hl_accept_factor(2_000_000, 1) < AIRMED._hl_accept_factor(200, 1)
        @test AIRMED._hl_accept_factor(2_000_000, 1) > 1.0
    end

    @testset "_parse_escalation_json / _escalation_to_json round-trip" begin
        good = AIRMED._escalation_to_json("cause text", "check the sensor")
        expl, rec, ok = AIRMED._parse_escalation_json(good)
        @test ok
        @test expl == "cause text"
        @test rec  == "check the sensor"

        expl2, rec2, ok2 = AIRMED._parse_escalation_json("not json at all")
        @test !ok2
        @test expl2 == "" && rec2 == ""
    end
end
